apiserver:
  build:
    context: api
    dockerfile: Dockerfile.api
  image: ddev_api
  volumes:
    - ./api:/usr/src/ddev 
  ports:
    - "8080:8080"
    - "5005:5005" 
  networks:
    - back-tier
  secrets:
    - postgres_password
watcher:
  build:
    context: api
    dockerfile: Dockerfile.api
  volumes:
    - ./api:/usr/src/ddev 
  command: mvn fizzed-watcher:run 
  networks:
    - back-tier