FROM maven:3.5.0-jdk-8-alpine AS appserver
WORKDIR /usr/src/ddev
COPY pom.xml .
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve 
COPY . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests 
EXPOSE 8080
CMD mvn spring-boot:run